import comtypes.gen.TaskbarLib as taskbarlib

class TaskbarLib:
    def ActivateTab(self, hwnd: int) -> None: ...
    def HrInit(self) -> None: ...
    def setProgressValue(self, hwnd: int, value: int, max: int) -> None: ...
    def SetProgressState(self, hwnd: int, type: int) -> None: ...

def GetModule(path: str) -> None: ...
def CreateObject(
    clsid: str, interface: type[taskbarlib.ITaskbarList3]
) -> TaskbarLib: ...
